repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml
          - id: debug-statements
            language_version: python3.12
          - id: check-added-large-files
          - id: name-tests-test
            args: [--pytest-test-first]

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.19.1
      hooks:
          - id: pyupgrade
            args: [--py312-plus]

    - repo: https://github.com/asottile/add-trailing-comma
      rev: v3.1.0
      hooks:
          - id: add-trailing-comma

    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
            language_version: python3.12

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.8.0
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.15.0
      hooks:
          - id: mypy
            language_version: python3.12
            additional_dependencies: [types-requests, types-PyYAML]
            args: [--ignore-missing-imports]
            exclude: ^tests/

    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
            require_serial: true
            args: [
                    "-rn",
                    "-sn",
                    "--max-line-length=120",
                    "--disable=missing-function-docstring,\
                    missing-module-docstring,\
                    missing-class-docstring,\
                    too-few-public-methods,\
                    c-extension-no-member",
                ]
