name: Code Quality

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.11'
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip3 install -r requirements.txt
        - name: install quality assurance tools
          run: |
            pip3 install black==23.3.0 mypy==1.4.1 pylint==2.17.4 types-setuptools==68.0.0.3
            chmod +x ./tests/test.sh
        - name: run QA tools
          run: |
            REPORT_FILE='qa_report.txt'
            REPORT_FILE_PATH="tests/${REPORT_FILE}"
            ./tests/test.sh > $REPORT_FILE_PATH
            mypy=$(grep -q 'Success: no issues found' $REPORT_FILE_PATH; echo $?)
            if [ "$mypy" -eq 0 ]; then
              echo "Mypy: Success"
            else
              echo "Mypy: Failure"
              cat $REPORT_FILE_PATH
              exit 1
            fi
            pylint_score=$(grep -oE 'Your code has been rated at ([0-9.]+)/10' $REPORT_FILE_PATH | grep -oE '[0-9]+\.[0-9]+')
            echo "Pylint score: $pylint_score"
            if [ "$(echo "$pylint_score > 8" | bc)" -eq 1 ]; then
              exit 0
            else
              exit 1
            fi